// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBE-P-LH0bdiI6decmew3PvTSbM9gk7do',
    appId: '1:194249209010:web:3f0959f561b03f94ab85ab',
    messagingSenderId: '194249209010',
    projectId: 'dhiwise-assignment-task',
    authDomain: 'dhiwise-assignment-task.firebaseapp.com',
    storageBucket: 'dhiwise-assignment-task.appspot.com',
    measurementId: 'G-SC43FVHZZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx9-_f0NYqN4SuNjTMLVXZ8IAgY1oIxw0',
    appId: '1:194249209010:android:ef2f4393c340af22ab85ab',
    messagingSenderId: '194249209010',
    projectId: 'dhiwise-assignment-task',
    storageBucket: 'dhiwise-assignment-task.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjxpLYKE8t38vjRZFYqhuk1LQ72QN5J4Q',
    appId: '1:194249209010:ios:42a76186060a5a6cab85ab',
    messagingSenderId: '194249209010',
    projectId: 'dhiwise-assignment-task',
    storageBucket: 'dhiwise-assignment-task.appspot.com',
    iosBundleId: 'com.example.dhiwiseFlutterAssigment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjxpLYKE8t38vjRZFYqhuk1LQ72QN5J4Q',
    appId: '1:194249209010:ios:8fd23b349bab4aefab85ab',
    messagingSenderId: '194249209010',
    projectId: 'dhiwise-assignment-task',
    storageBucket: 'dhiwise-assignment-task.appspot.com',
    iosBundleId: 'com.example.dhiwiseFlutterAssigment.RunnerTests',
  );
}
